In [39]:
import duckdb
dataset = duckdb.read_csv('vendas_completo.csv')

# **Analise de vendas completa**

- Nesse notebook, realizaremos as análises que necessitam do relatório de vendas completo, com a descrição dos itens vendidos, o códgio de estoque, quantidade e preço individual de cada item.

## **Buscando quantidade de itens vendidos**

- Feitas as devidas limpezas, podemos começar a conferir informações relevantes. A primeira delas, que pode fazer muita diferença no planejamento de estoque e em estratégia de vendas é saber como andam as vendas dos itens disponibilizados.

In [40]:
query = f"""
    SELECT 
        Description, SUM(Quantity) AS TotalQuantity
    FROM 
        dataset
    GROUP BY
        Description 
    ORDER BY
        TotalQuantity DESC
"""
resultado = duckdb.sql(query).df()
display(resultado)

                             Description  TotalQuantity
0            PAPER CRAFT , LITTLE BIRDIE        80995.0
1         MEDIUM CERAMIC TOP STORAGE JAR        77916.0
2      WORLD WAR 2 GLIDERS ASSTD DESIGNS        54415.0
3                JUMBO BAG RED RETROSPOT        46181.0
4     WHITE HANGING HEART T-LIGHT HOLDER        36725.0
...                                  ...            ...
3872       VINTAGE BEAD PINK JEWEL STAND            1.0
3873      CROCHET LILAC/RED BEAR KEYRING            1.0
3874  EASTER CRAFT IVY WREATH WITH CHICK            1.0
3875      DUSTY PINK CHRISTMAS TREE 30CM            1.0
3876                    DOLPHIN WINDMILL            1.0

[3877 rows x 2 columns]

## **Item mais vendido (por compra)**

- Agora podemos selecionar o item mais vendido em uma única compra

In [49]:
query = f"""
    SELECT 
        *
    FROM 
        dataset
    ORDER BY
        Quantity DESC
"""
resultado = duckdb.sql(query).df()
display(resultado)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/2011 9:15,2.08,16446,United Kingdom
1,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/2011 10:01,1.04,12346,United Kingdom
2,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,11/25/2011 15:57,0.00,13256,United Kingdom
3,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/2011 12:26,0.21,12901,United Kingdom
4,554868,22197,SMALL POPCORN HOLDER,4300,5/27/2011 10:52,0.72,13135,United Kingdom
...,...,...,...,...,...,...,...,...
397919,560689,84406B,CREAM CUPID HEARTS COAT HANGER,1,7/20/2011 11:55,4.15,15039,United Kingdom
397920,560650,22374,AIRLINE BAG VINTAGE JET SET RED,1,7/20/2011 11:38,4.25,15529,United Kingdom
397921,569136,22725,ALARM CLOCK BAKELIKE CHOCOLATE,1,9/30/2011 14:41,3.75,15834,United Kingdom
397922,563328,85114A,BLACK ENCHANTED FOREST PLACEMAT,1,8/15/2011 13:07,1.65,14606,United Kingdom
397923,567661,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,1,9/21/2011 15:06,0.65,13959,United Kingdom